# Site settings
title: "Avi Samloff"
email: avi.samloff@gmail.com
description: "Ramblings of Life, Love, Code, and Magic: The Gathering."
baseurl: ""
url: "http://AviSamloff.com"
title_description: "Ramblings of Life, Love, Code, and Magic: The Gathering."
title_image: "images/avi.jpg"
google_analytics: "UA-69143803-1"
# disqus_account: cartenoire
github_repository: https://github.com/theavish/theavish.github.io
# addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: theavish
github_username:  theavish
facebook_link: https://www.facebook.com/AviSamloff
linkedin_link: https://www.linkedin.com/in/avisamloff
# google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://stackoverflow.com/users/5314403/avi-samloff

# Footer
footer_left: "<small><a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte Noire</a> theme by Jacob Tomlinson</small>"
footer_right: "<small><a href=\"mailto:avi.samloff@gmail.com\">Email me</a></small>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]

#comments
comments :
  provider : disqus
  disqus :
    short_name : avisamloff
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light
