# Site settings
title: Avi Samloff
email: avi.samloff@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ramblings of Life, Love, Code, and Magic: The Gathering.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://AviSamloff.com" # the base hostname & protocol for your site
twitter_username: theavish
github_username:  theavish
facebook_username: AviSamloff

# Build settings
markdown: kramdown
